# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# define hostname
NAME = "mini-loop"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  config.vm.define NAME
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8181, host: 2223

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.memory = 8192
    vb.cpus = 2
    vb.name = NAME
  end

  config.vm.provision "shell", inline: "rm -rf /vagrant/scripts"
  config.vm.provision "file", source: "../scripts",  \
                              destination: "/vagrant/scripts"

  config.vm.provision "shell", inline: <<-SHELL
    # remove windows \r carriage return and run inline
    sed 's/\r$//' /vagrant/scripts/vagrant.sh | /bin/bash
  SHELL
  
  config.vm.provision "shell", inline: <<-SHELL
    # su - vagrant -c "/vagrant/scripts/01_install_miniloop.sh"
    su - vagrant -c "sed 's/\r$//' /vagrant/scripts/01_install_miniloop.sh | /bin/bash"
  SHELL
  
  # config.vm.provision "shell", inline: <<-SHELL
  #   # su - vagrant -c "/vagrant/scripts/02_seed_mojaloop.sh"
  #   su - vagrant -c "sed 's/\r$//' /vagrant/scripts/02_seed_mojaloop.sh | /bin/bash"
  # SHELL

  # config.vm.provision "shell", inline: <<-SHELL
  #   # su - vagrant -c "/vagrant/scripts/03_golden_path.sh"
  #   su - vagrant -c "sed 's/\r$//' /vagrant/scripts/03_golden_path.sh | /bin/bash"
  # SHELL
  
end
