# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# define hostname
NAME = "ml-k3d"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_check_update = true
  #config.vm.box_version = "1.0.282"
  config.vm.define NAME
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8181, host: 2223
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 3001, host: 3001
  config.vm.network "forwarded_port", guest: 6443, host: 8282
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9001, host: 9001
  # config.vm.synced_folder "../../ml-oss-sandbox", "/vagrant/ml-oss-sandbox"
  config.vm.synced_folder "../../demo-mojawallet", "/vagrant/demo-mojawallet"
  config.vm.synced_folder "../../ml-bootstrap", "/vagrant/ml-bootstrap"
  
  #config.vm.synced_folder "../../../learn", "/vagrant/learn"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 8192
    vb.cpus = 2
    vb.name = NAME
  end

  # config.vm.provision "file", source: "k3d-scripts",  \
  #                             destination: "/vagrant/k3d-scripts"
  
  # config.vm.provision "file", source: "install",  \
  # destination: "/vagrant/install"

  # config.vm.provision "shell", inline: <<-SHELL
  #   # remove windows \r carriage return and run inline
  #   sed 's/\r$//' /vagrant/k3s-scripts/vagrant.sh | /bin/bash
  # SHELL

  # config.vm.provision "shell", inline: <<-SHELL
  #   # su - vagrant -c "/vagrant/scripts/01_install_miniloop.sh"
  #   su - vagrant -c "sed 's/\r$//' /vagrant/scripts/01_install_miniloop.sh | /bin/bash"
  # SHELL
  
end