apiVersion: v1
kind: Service
metadata:
  name: python3-service
spec:
  type: NodePort
  selector:
    app: python3a
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8282
      nodePort: 30036

# to test kubectl run -i --tty curl1 --image=curlimages/curl -- sh
# then use curl against 8888