apiVersion: v1
description: FSPIOP Transfer API Service component Helm chart for Kubernetes
name: admin-api-svc
version: 12.0.0
appVersion: "11.1.6"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/ml-api-adapter
maintainers:
  - name: Murthy Kakarlamudi
    email: murthy@modusbox.com
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
dependencies:
  - name: common
    repository: "file://../common"
    tags:
      - moja-common
    version: 1.0.0
