# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-google")
  puts 'Installing vagrant-google Plugin...'
  system('vagrant plugin install vagrant-google')
end

unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

unless Vagrant.has_plugin?("vagrant-env")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-env')
end

Vagrant.configure("2") do |config|
  config.env.enable
  config.vm.box = "google/gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = ENV['GCP_PROJECT_ID']
    google.google_json_key_location = ENV['GCP_JSON_KEY_PATH']
    
    google.image_family = 'ubuntu-1804-lts'
    google.machine_type = 'n1-standard-4'
    google.disk_size = 30
    
    override.ssh.username = ENV['CGP_SSH_USERNAME']
    override.ssh.private_key_path = ENV['CGP_SSH_KEY']
  end

  config.vm.provision "shell", inline: "rm -rf /vagrant/scripts"
  config.vm.provision "file", source: "../scripts",  \
                              destination: "/vagrant/scripts"

  config.vm.provision "shell", inline: <<-SHELL
    echo "---- ensure /vagrant owned by vagrant  ---- "
    sleep 30
    uname2="$(stat --format '%U' "/vagrant")"
    if [ "x${uname2}" = "xvagrant" ]; then
      echo "/vagrant owner is vagrant : ok "
    else
      echo "changing /vagrant owner to vagrant"
      groupadd vagrant
      useradd vagrant -g vagrant -m  -b /home -s $(which bash)
      chown -R vagrant /vagrant 
    fi
    chmod g+w /vagrant 
  SHELL

  config.vm.provision "shell", 
    inline: "/bin/bash /vagrant/scripts/vagrant.sh" 
  
  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c "/vagrant/scripts/01_install_miniloop.sh"
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c "/vagrant/scripts/02_seed_mojaloop.sh"
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c "/vagrant/scripts/03_golden_path.sh"
  SHELL

end