# -*- mode: ruby -*-
# vi: set ft=ruby :

# required_plugins = %w( vagrant-omnibus vagrant-aws )
# required_plugins.each do |plugin|
#     exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
# end


unless Vagrant.has_plugin?("vagrant-google")
  puts 'Installing vagrant-google Plugin...'
  system('vagrant plugin install vagrant-google')
end

unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure("2") do |config|
  config.vm.box = "google/gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = "<your_project_id>"
    google.google_json_key_location = "<path_to_your_service_account_key>"
    
    google.image_family = 'ubuntu-1804-lts'
    google.machine_type = 'n1-standard-4'
    google.disk_size = 30
    
    override.ssh.username = "<your_username>"
    #override.ssh.private_key_path = "~/.ssh/id_rsa"
    override.ssh.private_key_path = "<your_private_ssh_key>"
  end

  config.vm.provision "shell", inline: "rm -rf /vagrant/scripts"
  config.vm.provision "file", source: "../scripts",  \
                              destination: "/vagrant/scripts"

  config.vm.provision "shell", inline: <<-SHELL
    echo "---- ensure /vagrant owned by vagrant  ---- "
    sleep 30
    uname2="$(stat --format '%U' "/vagrant")"
    if [ "x${uname2}" = "xvagrant" ]; then
      echo "/vagrant owner is vagrant : ok "
    else
      echo "changing /vagrant owner to vagrant"
      groupadd vagrant
      useradd vagrant -g vagrant -m  -b /home -s $(which bash)
      chown -R vagrant /vagrant 
    fi
    chmod g+w /vagrant 
  SHELL

  config.vm.provision "shell", inline: "/bin/bash /vagrant/scripts/vagrant.sh" 

  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c "/vagrant/scripts/mini-loop-install.sh"
  SHELL
  
  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c "/vagrant/scripts/setup-local-env.sh"
  SHELL
  
  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c "/vagrant/scripts/run-golden-path-local.sh"
  SHELL

end