annotations:
  category: Infrastructure
apiVersion: v2
# Please make sure that version and appVersion are always the same.
appVersion: 2.0.0
description: A Library Helm Chart for grouping common logic between bitnami charts. This chart is not deployable by itself.
home: https://github.com/mojaloop/charts/tree/master/mojaloop/common
icon: https://bitnami.com/downloads/logos/bitnami-mark.png
keywords:
  - common
  - helper
  - template
  - function
  - bitnami
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: common
sources:
  - https://github.com/mojaloop/charts
  - http://www.bitnami.com/
type: library
version: 2.0.0
