apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: ml-app
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app1
  name: hellodep
  namespace: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app1
  template:
    metadata:
      labels:
        app: hello-app1
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-container
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: helloingress
  namespace: ml-app
spec:
  rules:
  - host: fred
    http:
      paths:
      - backend:
          service:
            name: hello-service
            port:
              number: 8889
        path: /
        pathType: Prefix
      - backend:
          service:
            name: hello-service
            port:
              number: 8888
        path: /hellov2
        pathType: Prefix
