#!/usr/bin/bash

function check_aws_cli_config() {
  if ! command -v aws &>/dev/null; then
    echo "AWS CLI is not installed. Please install it first and then run 'aws configure' to set up your credentials."
    return 1
  fi

  if ! aws configure list &>/dev/null; then
    echo "AWS CLI is not configured. Please run 'aws configure' to set up your credentials."
    return 1
  fi

  echo "AWS CLI is configured."
  return 0
}

function configureNamespaceImagePullSecret() {
  if [ $# -ne 1 ]; then
    echo "Error: No namespace provided.
Please provide a namespace whose secret is to be patched. 
          
eg. $ patchSecret infrastructure
    "
    return 1
  fi

  NAMESPACE=$1

  echo 'Getting password from aws ECR ...'
  TOKEN=$(aws ecr get-login-password --region ap-south-1 | cut -d' ' -f6)
  echo 'Password acquired'
  echo 'Creating kubernetes secrets'
  kubectl delete secret regcred -n "$NAMESPACE"
  kubectl create secret docker-registry regcred --docker-server=419830066942.dkr.ecr.ap-south-1.amazonaws.com --docker-username=AWS --docker-password="$TOKEN" --docker-email=elijahokello90@gmail.com -n "$NAMESPACE"

  kubectl patch serviceaccount default -p "{\"imagePullSecrets\": [{\"name\": \"regcred\"}]}" -n "$NAMESPACE"
}

# Call function
check_aws_cli_config
configureNamespaceImagePullSecret $1
