apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
#  type: NodePort
  selector:
    app: apache-app3
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
#      nodePort: 30036

